title: edoalive.GitHub.io
description: 
google_analytics: 
show_downloads: false
theme: jekyll-theme-minimal
google_site_verification: VCGJcmfJ8Ujr3WvZ9uRfVtcdYmhhXIBz83CNoNoXuUw
webmaster_verifications:
  google: VCGJcmfJ8Ujr3WvZ9uRfVtcdYmhhXIBz83CNoNoXuUw
gems:
  - jekyll-mentions
  - jekyll-seo-tag
plugins:
  - jekyll-seo-tag
